# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QMenu,
    QMenuBar, QPlainTextEdit, QSizePolicy, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1600, 800)
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.load_file_action = QAction(MainWindow)
        self.load_file_action.setObjectName(u"load_file_action")
        self.save_file_line_action = QAction(MainWindow)
        self.save_file_line_action.setObjectName(u"save_file_line_action")
        self.reload_file_action = QAction(MainWindow)
        self.reload_file_action.setObjectName(u"reload_file_action")
        self.change_selected_item_action = QAction(MainWindow)
        self.change_selected_item_action.setObjectName(u"change_selected_item_action")
        self.get_selected_item_action = QAction(MainWindow)
        self.get_selected_item_action.setObjectName(u"get_selected_item_action")
        self.set_font_to_Consolas_action = QAction(MainWindow)
        self.set_font_to_Consolas_action.setObjectName(u"set_font_to_Consolas_action")
        self.set_font_to_JetBrains_Mono_action = QAction(MainWindow)
        self.set_font_to_JetBrains_Mono_action.setObjectName(u"set_font_to_JetBrains_Mono_action")
        self.set_light_theme_action = QAction(MainWindow)
        self.set_light_theme_action.setObjectName(u"set_light_theme_action")
        self.set_dark_theme_action = QAction(MainWindow)
        self.set_dark_theme_action.setObjectName(u"set_dark_theme_action")
        self.top_action = QAction(MainWindow)
        self.top_action.setObjectName(u"top_action")
        self.top_cancel_action = QAction(MainWindow)
        self.top_cancel_action.setObjectName(u"top_cancel_action")
        self.enlarge_font_size_action = QAction(MainWindow)
        self.enlarge_font_size_action.setObjectName(u"enlarge_font_size_action")
        self.reduce_font_size_action = QAction(MainWindow)
        self.reduce_font_size_action.setObjectName(u"reduce_font_size_action")
        self.open_file_action = QAction(MainWindow)
        self.open_file_action.setObjectName(u"open_file_action")
        self.reset_file_action = QAction(MainWindow)
        self.reset_file_action.setObjectName(u"reset_file_action")
        self.set_win_size_1600x800_action = QAction(MainWindow)
        self.set_win_size_1600x800_action.setObjectName(u"set_win_size_1600x800_action")
        self.set_win_size_1800x900_action = QAction(MainWindow)
        self.set_win_size_1800x900_action.setObjectName(u"set_win_size_1800x900_action")
        self.tab_action = QAction(MainWindow)
        self.tab_action.setObjectName(u"tab_action")
        self.back_action = QAction(MainWindow)
        self.back_action.setObjectName(u"back_action")
        self.cut_action = QAction(MainWindow)
        self.cut_action.setObjectName(u"cut_action")
        self.paste_action = QAction(MainWindow)
        self.paste_action.setObjectName(u"paste_action")
        self.undo_action = QAction(MainWindow)
        self.undo_action.setObjectName(u"undo_action")
        self.expand_sidebar_action = QAction(MainWindow)
        self.expand_sidebar_action.setObjectName(u"expand_sidebar_action")
        self.collapse_sidebar_action = QAction(MainWindow)
        self.collapse_sidebar_action.setObjectName(u"collapse_sidebar_action")
        self.shortcut_1_action = QAction(MainWindow)
        self.shortcut_1_action.setObjectName(u"shortcut_1_action")
        self.shortcut_2_action = QAction(MainWindow)
        self.shortcut_2_action.setObjectName(u"shortcut_2_action")
        self.shortcut_3_action = QAction(MainWindow)
        self.shortcut_3_action.setObjectName(u"shortcut_3_action")
        self.shortcut_4_action = QAction(MainWindow)
        self.shortcut_4_action.setObjectName(u"shortcut_4_action")
        self.shortcut_5_action = QAction(MainWindow)
        self.shortcut_5_action.setObjectName(u"shortcut_5_action")
        self.shortcut_6_action = QAction(MainWindow)
        self.shortcut_6_action.setObjectName(u"shortcut_6_action")
        self.shortcut_7_action = QAction(MainWindow)
        self.shortcut_7_action.setObjectName(u"shortcut_7_action")
        self.shortcut_8_action = QAction(MainWindow)
        self.shortcut_8_action.setObjectName(u"shortcut_8_action")
        self.shortcut_9_action = QAction(MainWindow)
        self.shortcut_9_action.setObjectName(u"shortcut_9_action")
        self.shortcut_0_action = QAction(MainWindow)
        self.shortcut_0_action.setObjectName(u"shortcut_0_action")
        self.replace_min_action = QAction(MainWindow)
        self.replace_min_action.setObjectName(u"replace_min_action")
        self.replace_equal_action = QAction(MainWindow)
        self.replace_equal_action.setObjectName(u"replace_equal_action")
        self.replace_add_action = QAction(MainWindow)
        self.replace_add_action.setObjectName(u"replace_add_action")
        self.charge_copy_action = QAction(MainWindow)
        self.charge_copy_action.setObjectName(u"charge_copy_action")
        self.charge_paste_action = QAction(MainWindow)
        self.charge_paste_action.setObjectName(u"charge_paste_action")
        self.cooldown_action = QAction(MainWindow)
        self.cooldown_action.setObjectName(u"cooldown_action")
        self.unit_dir_action = QAction(MainWindow)
        self.unit_dir_action.setObjectName(u"unit_dir_action")
        self.heroes_dir_action = QAction(MainWindow)
        self.heroes_dir_action.setObjectName(u"heroes_dir_action")
        self.root_dir_action = QAction(MainWindow)
        self.root_dir_action.setObjectName(u"root_dir_action")
        self.action_vpk = QAction(MainWindow)
        self.action_vpk.setObjectName(u"action_vpk")
        self.action_4 = QAction(MainWindow)
        self.action_4.setObjectName(u"action_4")
        self.action_5 = QAction(MainWindow)
        self.action_5.setObjectName(u"action_5")
        self.action_6 = QAction(MainWindow)
        self.action_6.setObjectName(u"action_6")
        self.save_file_text_action = QAction(MainWindow)
        self.save_file_text_action.setObjectName(u"save_file_text_action")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_5 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.frame_3)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.sidebar_frame = QFrame(self.frame_3)
        self.sidebar_frame.setObjectName(u"sidebar_frame")
        self.sidebar_frame.setMaximumSize(QSize(255, 16777215))
        self.sidebar_frame.setFrameShape(QFrame.StyledPanel)
        self.sidebar_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.sidebar_frame)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.search_lineEdit = QLineEdit(self.sidebar_frame)
        self.search_lineEdit.setObjectName(u"search_lineEdit")

        self.verticalLayout_2.addWidget(self.search_lineEdit)

        self.heroFiles_listWidget = QListWidget(self.sidebar_frame)
        QListWidgetItem(self.heroFiles_listWidget)
        self.heroFiles_listWidget.setObjectName(u"heroFiles_listWidget")

        self.verticalLayout_2.addWidget(self.heroFiles_listWidget)


        self.horizontalLayout_4.addWidget(self.sidebar_frame)

        self.frame_2 = QFrame(self.frame_3)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.view_tabWidget = QTabWidget(self.frame_2)
        self.view_tabWidget.setObjectName(u"view_tabWidget")
        self.line_tab = QWidget()
        self.line_tab.setObjectName(u"line_tab")
        self.line_tab.setEnabled(True)
        self.horizontalLayout = QHBoxLayout(self.line_tab)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.content_listWidget = QListWidget(self.line_tab)
        QListWidgetItem(self.content_listWidget)
        self.content_listWidget.setObjectName(u"content_listWidget")

        self.horizontalLayout.addWidget(self.content_listWidget)

        self.view_tabWidget.addTab(self.line_tab, "")
        self.text_tab = QWidget()
        self.text_tab.setObjectName(u"text_tab")
        self.horizontalLayout_2 = QHBoxLayout(self.text_tab)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.content_plainTextEdit = QPlainTextEdit(self.text_tab)
        self.content_plainTextEdit.setObjectName(u"content_plainTextEdit")

        self.horizontalLayout_2.addWidget(self.content_plainTextEdit)

        self.view_tabWidget.addTab(self.text_tab, "")

        self.horizontalLayout_3.addWidget(self.view_tabWidget)


        self.horizontalLayout_4.addWidget(self.frame_2)


        self.horizontalLayout_5.addWidget(self.frame_3)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 23))
        self.menu = QMenu(self.menubar)
        self.menu.setObjectName(u"menu")
        self.menu_2 = QMenu(self.menubar)
        self.menu_2.setObjectName(u"menu_2")
        self.menu_3 = QMenu(self.menubar)
        self.menu_3.setObjectName(u"menu_3")
        self.menu_4 = QMenu(self.menu_3)
        self.menu_4.setObjectName(u"menu_4")
        self.menu_5 = QMenu(self.menu_3)
        self.menu_5.setObjectName(u"menu_5")
        self.menu_6 = QMenu(self.menu_3)
        self.menu_6.setObjectName(u"menu_6")
        self.menu_6.setGeometry(QRect(464, 176, 120, 200))
        self.menu_7 = QMenu(self.menubar)
        self.menu_7.setObjectName(u"menu_7")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.menu.addAction(self.save_file_line_action)
        self.menu.addAction(self.save_file_text_action)
        self.menu.addAction(self.reload_file_action)
        self.menu.addAction(self.open_file_action)
        self.menu.addAction(self.reset_file_action)
        self.menu_2.addAction(self.change_selected_item_action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.shortcut_1_action)
        self.menu_2.addAction(self.shortcut_2_action)
        self.menu_2.addAction(self.shortcut_3_action)
        self.menu_2.addAction(self.shortcut_4_action)
        self.menu_2.addAction(self.shortcut_5_action)
        self.menu_2.addAction(self.shortcut_6_action)
        self.menu_2.addAction(self.shortcut_7_action)
        self.menu_2.addAction(self.shortcut_8_action)
        self.menu_2.addAction(self.shortcut_9_action)
        self.menu_2.addAction(self.shortcut_0_action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.replace_min_action)
        self.menu_2.addAction(self.replace_equal_action)
        self.menu_2.addAction(self.replace_add_action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.cooldown_action)
        self.menu_2.addAction(self.charge_copy_action)
        self.menu_2.addAction(self.charge_paste_action)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.tab_action)
        self.menu_2.addAction(self.back_action)
        self.menu_2.addAction(self.cut_action)
        self.menu_2.addAction(self.paste_action)
        self.menu_2.addAction(self.undo_action)
        self.menu_3.addAction(self.menu_4.menuAction())
        self.menu_3.addAction(self.menu_5.menuAction())
        self.menu_3.addAction(self.menu_6.menuAction())
        self.menu_4.addAction(self.enlarge_font_size_action)
        self.menu_4.addAction(self.reduce_font_size_action)
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.set_font_to_JetBrains_Mono_action)
        self.menu_4.addAction(self.set_font_to_Consolas_action)
        self.menu_5.addAction(self.set_light_theme_action)
        self.menu_5.addAction(self.set_dark_theme_action)
        self.menu_6.addAction(self.top_action)
        self.menu_6.addAction(self.top_cancel_action)
        self.menu_6.addSeparator()
        self.menu_6.addAction(self.expand_sidebar_action)
        self.menu_6.addAction(self.collapse_sidebar_action)
        self.menu_6.addSeparator()
        self.menu_6.addAction(self.set_win_size_1600x800_action)
        self.menu_6.addAction(self.set_win_size_1800x900_action)
        self.menu_7.addAction(self.root_dir_action)
        self.menu_7.addAction(self.unit_dir_action)
        self.menu_7.addAction(self.heroes_dir_action)
        self.menu_7.addAction(self.action_6)
        self.menu_7.addSeparator()
        self.menu_7.addAction(self.action_4)
        self.menu_7.addAction(self.action_5)
        self.menu_7.addSeparator()
        self.menu_7.addAction(self.action_vpk)

        self.retranslateUi(MainWindow)

        self.view_tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u7f6e\u9876", None))
        self.load_file_action.setText(QCoreApplication.translate("MainWindow", u"\u8f7d\u5165", None))
        self.save_file_line_action.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58(\u884c)", None))
#if QT_CONFIG(shortcut)
        self.save_file_line_action.setShortcut(QCoreApplication.translate("MainWindow", u"S", None))
#endif // QT_CONFIG(shortcut)
        self.reload_file_action.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u8f7d", None))
#if QT_CONFIG(shortcut)
        self.reload_file_action.setShortcut(QCoreApplication.translate("MainWindow", u"R", None))
#endif // QT_CONFIG(shortcut)
        self.change_selected_item_action.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u9009\u4e2d\u884c", None))
#if QT_CONFIG(shortcut)
        self.change_selected_item_action.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.get_selected_item_action.setText(QCoreApplication.translate("MainWindow", u"\u5199\u5165\u9009\u4e2d\u884c", None))
        self.set_font_to_Consolas_action.setText(QCoreApplication.translate("MainWindow", u"Consolas", None))
        self.set_font_to_JetBrains_Mono_action.setText(QCoreApplication.translate("MainWindow", u"JetBrains Mono", None))
        self.set_light_theme_action.setText(QCoreApplication.translate("MainWindow", u"\u4eae\u8272", None))
        self.set_dark_theme_action.setText(QCoreApplication.translate("MainWindow", u"\u6697\u8272", None))
        self.top_action.setText(QCoreApplication.translate("MainWindow", u"\u7f6e\u9876", None))
#if QT_CONFIG(shortcut)
        self.top_action.setShortcut(QCoreApplication.translate("MainWindow", u"T", None))
#endif // QT_CONFIG(shortcut)
        self.top_cancel_action.setText(QCoreApplication.translate("MainWindow", u"\u53d6\u6d88\u7f6e\u9876", None))
#if QT_CONFIG(shortcut)
        self.top_cancel_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.enlarge_font_size_action.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927\u5b57\u4f53", None))
#if QT_CONFIG(shortcut)
        self.enlarge_font_size_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.reduce_font_size_action.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f\u5b57\u4f53", None))
#if QT_CONFIG(shortcut)
        self.reduce_font_size_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.open_file_action.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00", None))
#if QT_CONFIG(shortcut)
        self.open_file_action.setShortcut(QCoreApplication.translate("MainWindow", u"O", None))
#endif // QT_CONFIG(shortcut)
        self.reset_file_action.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u7f6e", None))
#if QT_CONFIG(shortcut)
        self.reset_file_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.set_win_size_1600x800_action.setText(QCoreApplication.translate("MainWindow", u"1600x800", None))
        self.set_win_size_1800x900_action.setText(QCoreApplication.translate("MainWindow", u"1800x900", None))
        self.tab_action.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u8fdb", None))
#if QT_CONFIG(shortcut)
        self.tab_action.setShortcut(QCoreApplication.translate("MainWindow", u"Tab", None))
#endif // QT_CONFIG(shortcut)
        self.back_action.setText(QCoreApplication.translate("MainWindow", u"\u9000\u683c", None))
#if QT_CONFIG(shortcut)
        self.back_action.setShortcut(QCoreApplication.translate("MainWindow", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.cut_action.setText(QCoreApplication.translate("MainWindow", u"\u526a\u5207", None))
#if QT_CONFIG(shortcut)
        self.cut_action.setShortcut(QCoreApplication.translate("MainWindow", u"X", None))
#endif // QT_CONFIG(shortcut)
        self.paste_action.setText(QCoreApplication.translate("MainWindow", u"\u7c98\u8d34", None))
#if QT_CONFIG(shortcut)
        self.paste_action.setShortcut(QCoreApplication.translate("MainWindow", u"V", None))
#endif // QT_CONFIG(shortcut)
        self.undo_action.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u56de", None))
#if QT_CONFIG(shortcut)
        self.undo_action.setShortcut(QCoreApplication.translate("MainWindow", u"Z", None))
#endif // QT_CONFIG(shortcut)
        self.expand_sidebar_action.setText(QCoreApplication.translate("MainWindow", u"\u4fa7\u680f\u5c55\u5f00", None))
#if QT_CONFIG(shortcut)
        self.expand_sidebar_action.setShortcut(QCoreApplication.translate("MainWindow", u"`", None))
#endif // QT_CONFIG(shortcut)
        self.collapse_sidebar_action.setText(QCoreApplication.translate("MainWindow", u"\u4fa7\u680f\u6536\u8d77", None))
#if QT_CONFIG(shortcut)
        self.collapse_sidebar_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+`", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_1_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e1", None))
#if QT_CONFIG(shortcut)
        self.shortcut_1_action.setShortcut(QCoreApplication.translate("MainWindow", u"1", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_2_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e2", None))
#if QT_CONFIG(shortcut)
        self.shortcut_2_action.setShortcut(QCoreApplication.translate("MainWindow", u"2", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_3_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e3", None))
#if QT_CONFIG(shortcut)
        self.shortcut_3_action.setShortcut(QCoreApplication.translate("MainWindow", u"3", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_4_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e4", None))
#if QT_CONFIG(shortcut)
        self.shortcut_4_action.setShortcut(QCoreApplication.translate("MainWindow", u"4", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_5_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e5", None))
#if QT_CONFIG(shortcut)
        self.shortcut_5_action.setShortcut(QCoreApplication.translate("MainWindow", u"5", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_6_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e6", None))
#if QT_CONFIG(shortcut)
        self.shortcut_6_action.setShortcut(QCoreApplication.translate("MainWindow", u"6", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_7_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e7", None))
#if QT_CONFIG(shortcut)
        self.shortcut_7_action.setShortcut(QCoreApplication.translate("MainWindow", u"7", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_8_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e8", None))
#if QT_CONFIG(shortcut)
        self.shortcut_8_action.setShortcut(QCoreApplication.translate("MainWindow", u"8", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_9_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e9", None))
#if QT_CONFIG(shortcut)
        self.shortcut_9_action.setShortcut(QCoreApplication.translate("MainWindow", u"9", None))
#endif // QT_CONFIG(shortcut)
        self.shortcut_0_action.setText(QCoreApplication.translate("MainWindow", u"\u5feb\u6377\u952e0", None))
#if QT_CONFIG(shortcut)
        self.shortcut_0_action.setShortcut(QCoreApplication.translate("MainWindow", u"0", None))
#endif // QT_CONFIG(shortcut)
        self.replace_min_action.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362\u6210-", None))
#if QT_CONFIG(shortcut)
        self.replace_min_action.setShortcut(QCoreApplication.translate("MainWindow", u"-", None))
#endif // QT_CONFIG(shortcut)
        self.replace_equal_action.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362\u6210=", None))
#if QT_CONFIG(shortcut)
        self.replace_equal_action.setShortcut(QCoreApplication.translate("MainWindow", u"=", None))
#endif // QT_CONFIG(shortcut)
        self.replace_add_action.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362\u6210+", None))
#if QT_CONFIG(shortcut)
        self.replace_add_action.setShortcut(QCoreApplication.translate("MainWindow", u"+", None))
#endif // QT_CONFIG(shortcut)
        self.charge_copy_action.setText(QCoreApplication.translate("MainWindow", u"\u5145\u80fd\u590d\u5236", None))
#if QT_CONFIG(shortcut)
        self.charge_copy_action.setShortcut(QCoreApplication.translate("MainWindow", u"G", None))
#endif // QT_CONFIG(shortcut)
        self.charge_paste_action.setText(QCoreApplication.translate("MainWindow", u"\u5145\u80fd\u7c98\u8d34", None))
#if QT_CONFIG(shortcut)
        self.charge_paste_action.setShortcut(QCoreApplication.translate("MainWindow", u"H", None))
#endif // QT_CONFIG(shortcut)
        self.cooldown_action.setText(QCoreApplication.translate("MainWindow", u"\u51b7\u5374\u4fee\u6539", None))
#if QT_CONFIG(shortcut)
        self.cooldown_action.setShortcut(QCoreApplication.translate("MainWindow", u"D", None))
#endif // QT_CONFIG(shortcut)
        self.unit_dir_action.setText(QCoreApplication.translate("MainWindow", u"\u5355\u4f4d\u76ee\u5f55", None))
#if QT_CONFIG(shortcut)
        self.unit_dir_action.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.heroes_dir_action.setText(QCoreApplication.translate("MainWindow", u"\u82f1\u96c4\u76ee\u5f55", None))
#if QT_CONFIG(shortcut)
        self.heroes_dir_action.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.root_dir_action.setText(QCoreApplication.translate("MainWindow", u"\u6839\u76ee\u5f55", None))
#if QT_CONFIG(shortcut)
        self.root_dir_action.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.action_vpk.setText(QCoreApplication.translate("MainWindow", u"\u751f\u6210vpk", None))
        self.action_4.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u91d1\u5e01\u7ecf\u9a8c", None))
        self.action_5.setText(QCoreApplication.translate("MainWindow", u"\u4fee\u6539\u4e2d\u7acb\u7269\u54c1", None))
        self.action_6.setText(QCoreApplication.translate("MainWindow", u"\u6e38\u620f\u76ee\u5f55", None))
        self.save_file_text_action.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58(\u6587\u672c)", None))
#if QT_CONFIG(shortcut)
        self.save_file_text_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.search_lineEdit.setText("")
        self.search_lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"\u641c\u7d22...", None))

        __sortingEnabled = self.heroFiles_listWidget.isSortingEnabled()
        self.heroFiles_listWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.heroFiles_listWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"\u672a\u627e\u5230\u6587\u4ef6\u5217\u8868...", None));
        self.heroFiles_listWidget.setSortingEnabled(__sortingEnabled)


        __sortingEnabled1 = self.content_listWidget.isSortingEnabled()
        self.content_listWidget.setSortingEnabled(False)
        ___qlistwidgetitem1 = self.content_listWidget.item(0)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"\u672a\u52a0\u8f7d\u6587\u4ef6...", None));
        self.content_listWidget.setSortingEnabled(__sortingEnabled1)

        self.view_tabWidget.setTabText(self.view_tabWidget.indexOf(self.line_tab), QCoreApplication.translate("MainWindow", u"\u884c\u89c6\u56fe", None))
        self.content_plainTextEdit.setPlainText(QCoreApplication.translate("MainWindow", u"\u672a\u52a0\u8f7d\u6587\u4ef6...", None))
        self.view_tabWidget.setTabText(self.view_tabWidget.indexOf(self.text_tab), QCoreApplication.translate("MainWindow", u"\u6587\u672c\u89c6\u56fe", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menu_2.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menu_3.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menu_4.setTitle(QCoreApplication.translate("MainWindow", u"\u5b57\u4f53", None))
        self.menu_5.setTitle(QCoreApplication.translate("MainWindow", u"\u4e3b\u9898", None))
        self.menu_6.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
        self.menu_7.setTitle(QCoreApplication.translate("MainWindow", u"\u811a\u672c", None))
    # retranslateUi

